import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author edwin
 */
public class Tenant extends javax.swing.JFrame {
    static Connection conn;
    static PreparedStatement pst;
    
    
    

    /**
     * Creates new form AddExpensePage
     */
    public Tenant() {
	initComponents();
	setLocationRelativeTo(null);
	setVisible(true);
	setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        expenseInputPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        contactNumberInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        fistNameInput = new javax.swing.JTextField();
        ageBox = new javax.swing.JSpinner();
        middleNameLabel = new javax.swing.JLabel();
        pinInput = new javax.swing.JTextField();
        middleNameInput = new javax.swing.JTextField();
        roomIdInput = new javax.swing.JTextField();
        roomIdLabel = new javax.swing.JLabel();
        contractBox = new javax.swing.JComboBox<>();
        pinLabel = new javax.swing.JLabel();
        contractLabel = new javax.swing.JLabel();
        femaleRadio = new javax.swing.JRadioButton();
        maleRadio = new javax.swing.JRadioButton();
        registerTenantLabel = new javax.swing.JLabel();
        addExpenseGoBackButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        expenseInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        expenseInputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        expenseInputPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        firstNameLabel.setText("First Name");
        expenseInputPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        ageLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        ageLabel.setText("Age");
        expenseInputPanel.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, 30));

        contactNumberLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        contactNumberLabel.setText("Contact Number");
        expenseInputPanel.add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        genderLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        genderLabel.setText("Gender");
        expenseInputPanel.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 120, 30));
        expenseInputPanel.add(contactNumberInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 340, 40));
        expenseInputPanel.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 40));

        lastNameLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        lastNameLabel.setText("Last Name");
        expenseInputPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 120, 30));
        expenseInputPanel.add(fistNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 40));
        expenseInputPanel.add(ageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 40));

        middleNameLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        middleNameLabel.setText("Middle Name");
        expenseInputPanel.add(middleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));
        expenseInputPanel.add(pinInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 40));
        expenseInputPanel.add(middleNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 40));
        expenseInputPanel.add(roomIdInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 40));

        roomIdLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        roomIdLabel.setText("Room ID");
        expenseInputPanel.add(roomIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 30));

        contractBox.setBackground(new java.awt.Color(255, 255, 254));
        contractBox.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        contractBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 month", "3 months", "6 months", "9 months", "12 months" }));
        contractBox.setFocusable(false);
        expenseInputPanel.add(contractBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 150, 40));

        pinLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        pinLabel.setText("PIN");
        expenseInputPanel.add(pinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 30));

        contractLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 15)); // NOI18N
        contractLabel.setText("Contract");
        expenseInputPanel.add(contractLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 30));

        femaleRadio.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        femaleRadio.setText("Female");
        femaleRadio.setContentAreaFilled(false);
        femaleRadio.setFocusPainted(false);
        expenseInputPanel.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 80, -1));

        maleRadio.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        maleRadio.setText("Male");
        maleRadio.setContentAreaFilled(false);
        maleRadio.setFocusPainted(false);
        expenseInputPanel.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        registerTenantLabel.setFont(new java.awt.Font("Archivo SemiBold", 0, 28)); // NOI18N
        registerTenantLabel.setText("Register Tenant");

        addExpenseGoBackButton.setBackground(new java.awt.Color(254, 254, 254));
        addExpenseGoBackButton.setText("Back");
        addExpenseGoBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExpenseGoBackButton.setFocusable(false);
        addExpenseGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseGoBackButtonActionPerformed(evt);
            }
        });

        addExpenseButton.setBackground(new java.awt.Color(254, 254, 254));
        addExpenseButton.setText("Register Tenant");
        addExpenseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExpenseButton.setFocusable(false);
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(addExpenseGoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(expenseInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registerTenantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(registerTenantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addExpenseGoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addExpenseGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseGoBackButtonActionPerformed
        // TODO add your handling code here:
	dispose();
    }//GEN-LAST:event_addExpenseGoBackButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	try {
	UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
	    // Handle any exceptions
	     ex.printStackTrace();
	}

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Tenant().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JButton addExpenseGoBackButton;
    private javax.swing.JSpinner ageBox;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField contactNumberInput;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JComboBox<String> contractBox;
    private javax.swing.JLabel contractLabel;
    private javax.swing.JPanel expenseInputPanel;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField fistNameInput;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField middleNameInput;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField pinInput;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JLabel registerTenantLabel;
    private javax.swing.JTextField roomIdInput;
    private javax.swing.JLabel roomIdLabel;
    // End of variables declaration//GEN-END:variables
}
